config/routes.rb
Rails.application.routes.draw do

  
  resource :ballot_paper, path: '/vote', only: [:create, :new, :show]
  resources :days, path: '/days', controller: :days do
    resources :pitches, only: [:create, :edit, :update, :destroy]
    resources :voting_rounds, only: [:new, :index, :create, :show] do
    end
  end
  resources :results, only: [:index, :show]

  get '/auth/:provider/callback' => 'sessions#create', as: 'login'
  get '/signout' => 'sessions#destroy', as: 'signout'

  root 'days#index'

  

end

app/models/voting_round.rb
class VotingRound < ActiveRecord::Base
  belongs_to :day
  delegate :cohort_name, :location, :pitch_date, to: :day, allow_nil: true, prefix: false
  has_many :candidates, :dependent => :destroy
  has_many :votes, :dependent => :destroy

  def self.closed
    where(is_open: false)
  end
  
  def self.max_for_day day
    VotingRound.where(day: day).maximum("id")
  end

  def self.open_rounds
    VotingRound.where(is_open: true)
  end

  def update_candidates arr
    existing = Candidate.pitch_ids_for_round(self.id)
    arr = arr.uniq
    arr.each do |pitch_id|
      if existing.include? pitch_id
        existing.delete pitch_id
      else
        self.candidates << Candidate.create({ pitch_id: pitch_id})
      end
    end
    Candidate.delete_pitches_from_round(self.id, existing)
    self.reload
  end

  def self.create_with_candidates(day_id, candidate_ids)
    vr = VotingRound.new({ day_id: day_id })
    current_max = VotingRound.max_for_day(day_id)
    current_max = 0 if !current_max 
    vr.round_number = 1 + current_max
    vr.save
    candidate_ids.each {|id| vr.candidates << Candidate.create({ pitch_id: id}) }
    vr
  end
end

app/controllers/voting_rounds_controller.rb
class VotingRoundsController < ApplicationController
  skip_before_action :require_staff_login, only:[:index, :show]
  
  def index
    day_id = params[:day_id]
    @day = Day.find(day_id)
    @rounds = VotingRound.where(day_id: day_id).order('id desc')
  end


  def new
    @day = Day.find(params[:day_id])
    @voting_round = VotingRound.new
  end

  def create
    day_id = params[:day_id]
    pitch_ids = []
    params[:pitches].each do |k,v|
      pitch_ids.push k[1..-1]
    end
    vr = VotingRound.create_with_candidates(day_id, pitch_ids)
    if vr.save
      redirect_to day_voting_rounds_path, notice: 'Voting round created'
    else
      redirect_to day_voting_rounds_path, alert: 'Failed to create voting round created'
    end

  end
end

app/views/voting_rounds/index.html.erb
<h1>Voting rounds for <%= @day.cohort_name %></h1>
<table>
	<tr>
		<th>Round number</th>
		<th>Open</th>
		<th>Action</th>
	</tr>
<% @rounds.each do |round| %>
  <tr>
  	<td><%= round.round_number %></td>
  	<td><%= round.is_open %></td>
  	<% if round.is_open %>
  	  <td><%= link_to 'Cast a vote', new_ballot_paper_path({round_id: round.id}) %></td>
  	<% else %>
  	  <td><%= link_to 'View results', results_path(round) %></td>
  	<% end %>
  	
  </tr>
<% end %>
</table>
<% if staff_logged_in %>
  <%= link_to 'Create a round', new_day_voting_round_path(@day) %>
<% end %>

app/views/voting_rounds/new.html.erb
<h1>Create a new voting round for <%= @day.cohort_name %></h1>

<%= form_for [@day, @voting_round] do |f| %>

<table data-id="round_candidates">
	<tr>
		<th>Proposer</th>
		<th>Name</th>
		<th>Include in round?<br> <a data-purpose="select-all" href="#">Select all</a>
    <a data-purpose="clear-all" href="#">Clear all</a> </th>
	</tr>
  <% @day.pitches.each do |p| %>
    <tr>
    	<td><%= p.proposer %></td>
    	<td><%= p.name %></td>
    	<td><%= check_box_tag "pitches[p#{p.id}]", 1, false, {class: 'pitch_cb'}  %> </td>
    </tr>
  <% end %>
 </table>
<%= f.submit %>
<% end %>