config/routes.rb
Rails.application.routes.draw do

  
  resource :ballot_paper, path: '/vote', only: [:create, :new, :show]
  resources :days, path: '/days', controller: :days do
    resources :pitches, only: [:create, :edit, :update, :destroy]
    resources :voting_rounds, only: [:new, :index, :create, :show] do
    end
  end
  resources :results, only: [:index, :show]

  get '/auth/:provider/callback' => 'sessions#create', as: 'login'
  get '/signout' => 'sessions#destroy', as: 'signout'

  root 'days#index'

  

end

app/models/pitch.rb
class Pitch < ActiveRecord::Base
  belongs_to :day
  delegate :cohort_name, :location, :pitch_date, to: :day, allow_nil: true, prefix: false
  has_many :candidates, :dependent => :restrict_with_exception
end

app/controllers/pitches_controller.rb
class PitchesController < ApplicationController

  def edit
    @day = Day.find(params[:day_id])
    @pitch = Pitch.find(params[:id])
  end

  def update
    @pitch = Pitch.find(params[:id])
    @pitch.update_attributes!(pitch_params)
    redirect_to day_path(@pitch.day_id)
  end

  def create
    pitch = Pitch.new(pitch_params)
    if pitch.save
      render partial: 'pitch', locals: {pitch: pitch, day: pitch.day}
    else
      render text: "Error", status: :bad_request
    end

  end
  
  def destroy
    pitch = Pitch.find(params[:id])
    if pitch.destroy
      redirect_to day_path(pitch.day), notice: 'Pitch deleted'
    else
      redirect_to day_path(pitch.day), alert: 'Failed to delete pitch'
    end
  end

  def pitch_params
    params.require(:pitch).permit(:day_id, :proposer, :name, :description)
  end
end

app/views/pitches/_pitch.html.erb
    	<tr>
    	  <td class="proposer"><%= pitch.proposer %></td>
    	  <td class="pitch_name"><%= pitch.name %></td>
    	  <td class="pitch_description"><%= pitch.description %></td>
        <td class="pitch_actions">
        	<% if staff_logged_in %>
          <%= link_to 'Edit', edit_day_pitch_path(day, pitch)%>
          <%= link_to 'Delete', day_pitch_path(day, pitch), method: :delete, confirm:'Are you sure you want to delete' %>
          <% end %>
        </td>
	
    	</tr>

app/views/pitches/edit.html.erb
<%= form_for [@day, @pitch] do |f| %>
  <%= f.label :day %>
  <%= f.select(:day_id, Day.all.collect {|u| [u.cohort_name, u.id]}) %>

  <%= f.label :proposer %>
  <%= f.text_field :proposer %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.submit %>

<% end %>