config/routes.rb
Rails.application.routes.draw do

  
  resource :ballot_paper, path: '/vote', only: [:create, :new, :show]
  resources :days, path: '/days', controller: :days do
    resources :pitches, only: [:create, :edit, :update, :destroy]
    resources :voting_rounds, only: [:new, :index, :create, :show] do
    end
  end
  resources :results, only: [:index, :show]

  get '/auth/:provider/callback' => 'sessions#create', as: 'login'
  get '/signout' => 'sessions#destroy', as: 'signout'

  root 'days#index'

  

end

app/models/day.rb
class Day < ActiveRecord::Base
  has_many :pitches, -> { order(:id) }, :dependent => :restrict_with_exception
  has_many :voting_rounds, :dependent => :restrict_with_exception
  validates_presence_of :cohort_name, :location, :pitch_date

  def self.default_order
    order('pitch_date desc, location desc')
  end
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  skip_before_action :require_staff_login, only:[:index, :show]
  def index
    @days = Day.default_order
  end

  def show
    @day = Day.find(params[:id])
    @pitch=Pitch.new
  end

  def new
    @day = Day.new
  end

  def create
    @day = Day.create(day_params)
    if @day.save
      redirect_to days_path, notice: 'New day saved'
    else
      render 'new'
    end
  end
  
  def destroy
    @day = Day.find(params[:id])
    if @day.pitches.length > 0
      redirect_to days_path, alert: "Can't delete a pitch day once pitches are added."
    else
      @day.destroy
      redirect_to days_path, notice: "Removed pitch day #{@day.id}"
    end
  end

  def day_params
    params.require(:day).permit(:cohort_name, :location, :pitch_date)
  end

end

app/views/days/index.html.erb
<table>
  <tr>
  	<th class="location">Location</th>
  	<th class="cohort_name">Cohort name</th>
  	<th class="details_link">Actions</th>
  </tr>

<% @days.each do |day| %>
  <tr>
  	<td class="location"><%= day.location %></td>
  	<td class="cohort_name"><%= day.cohort_name %></td>
  	<td class="details_link"><%= link_to 'Details', day_path(day) %> <%= link_to 'Delete', day_path(day), method: :delete %> </td>
  </tr>
<% end %>
</table>

<% if staff_logged_in %>
  <%= link_to 'Add a day', new_day_path %>
<% end %>

app/views/days/new.html.erb
<h1>Create a new pitch day</h1>
<% if @day.errors.any? %>
  
  <ul>
    <% @day.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>

<% end %>
<%= form_for @day, url: {action: :create } do |f| %>
  <%= f.label :cohort_name %>
  <%= f.text_field :cohort_name %>

  <%= f.label :location %>
  <%= f.select :location, locations: ['NYC', 'CHI', 'SF'] %>

  <%= f.label :pitch_date %>
  <%= f.date_field :pitch_date %>

  <%= f.submit %>
<% end %>

app/views/days/show.html.erb
<h1><%= @day.cohort_name %></h1>

<h2>Pitch details</h2>
<table id="pitches">
	<tr>
		<th class="proposer"  >Proposer</th>
		<th class="pitch_name" >Pitch name</th>
		<th>Pitch Description</th>
    <th id="pitch_actions">Actions</th>
	</tr>

    <% @day.pitches.each do |pitch| %>
      <%= render partial: 'pitches/pitch', locals: {pitch: pitch, day: @day} %> 
    <% end %>
</table>


<%= link_to 'Voting rounds', day_voting_rounds_path(@day) %>

<% if staff_logged_in %>
<h3> Add a pitch</h3>
<%= form_for [@day, @pitch] do |f| %>

  <%= f.hidden_field :day_id, value: @day.id %>

  <%= f.label :proposer %> 
  <%= f.text_field :proposer %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.submit %>

<% end %>
<% end %>