config/routes.rb
Rails.application.routes.draw do

  
  resource :ballot_paper, path: '/vote', only: [:create, :new, :show]
  resources :days, path: '/days', controller: :days do
    resources :pitches, only: [:create, :edit, :update, :destroy]
    resources :voting_rounds, only: [:new, :index, :create, :show] do
    end
  end
  resources :results, only: [:index, :show]

  get '/auth/:provider/callback' => 'sessions#create', as: 'login'
  get '/signout' => 'sessions#destroy', as: 'signout'

  root 'days#index'

  

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

<% if current_user %>

    <% if staff_logged_in %>
    <li><%= link_to 'Create a day', new_day_path %></li>
    <% end %>

  <% if @day %>
    <li><%= link_to 'Cast a vote', new_ballot_paper_path %></li>
  <% end %>
<li><%= link_to "Sign out #{current_user.name}", signout_path %></li>
<% else %>
  <li><%= link_to 'Sign in', '/auth/dbc' %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Pitch Vote" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Pitch Vote" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>